# Generated by Django 3.1.2 on 2020-11-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaW', '0002_auto_20201113_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
