# Generated by Django 3.1.2 on 2020-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AplikacjaW', '0003_delete_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
