# Generated by Django 3.1.2 on 2020-12-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AplikacjaW', '0006_auto_20201217_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('idklienta', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.TextField(blank=True, null=True)),
                ('nazwisko', models.TextField(blank=True, null=True)),
                ('telefonkontaktowy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'klienci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('idsprzetu', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(blank=True, max_length=30, null=True)),
                ('rozmiar', models.SmallIntegerField(blank=True, null=True)),
                ('kolor', models.CharField(blank=True, max_length=20, null=True)),
                ('czyuszkodzony', models.BooleanField(blank=True, null=True)),
                ('czywypozyczony', models.BooleanField(blank=True, null=True)),
                ('cena', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'magazyn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('idpracownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(blank=True, max_length=30, null=True)),
                ('nazwisko', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'pracownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('idwypozyczenia', models.AutoField(primary_key=True, serialize=False)),
                ('datawypozyczenia', models.DateField(blank=True, null=True)),
                ('datazakonczeniawypozyczenia', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wypozyczenia',
                'managed': False,
            },
        ),
    ]
